name: Trigger COPR Build for Fedora Rawhide

on:
  # Trigger on push, but only for fedora-rawhide SPECS and SOURCES changes
  push:
    paths:
    - fedora-rawhide/SPECS/*.spec
    - fedora-rawhide/SOURCES/**

  # Enables manual triggering of the workflow
  workflow_dispatch:

jobs:
  build-copr-rawhide:
    runs-on: ubuntu-latest

    # Defines the Fedora container for this job
    container:
      image: fedora:latest

    steps:
      # 1. Install copr-cli
      - name: Install copr-cli
        run: dnf install -y copr-cli git git-lfs jq

      # 2. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          lfs: true

      # 3. Run the build script for Fedora Rawhide only.
      - name: Run COPR build script for Fedora Rawhide (best effort)
        run: ./build.sh fedora-rawhide
        # Inject secrets into the container as environment variables
        env:
          COPR_CONFIG: ${{ secrets.COPR_CONFIG }}
